[package]
name = "rusty_mos"
version = "1.0.3"
edition = "2021"
authors = ["kai_Ker <22373080@buaa.edu.cn>"]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
mipsel = []
